---
title: "My Blog"
author: "Jayanta Kumar Kamila"
description: "A personal blog created using Jekyll."
baseurl: "/blogs"
url: "https://jayantakr.github.io" ("https://username-github.github.io")
theme: minima
